"""Forced initial migration from empty db

Revision ID: 036cfce421b4
Revises: 
Create Date: 2025-12-05 00:39:12.595195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036cfce421b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('foto_path', sa.String(length=255), nullable=True),
    sa.Column('bio_intro', sa.Text(), nullable=True),
    sa.Column('bio_lista_titulo', sa.String(length=255), nullable=True),
    sa.Column('bio_lista_itens', sa.Text(), nullable=True),
    sa.Column('bio_conclusao', sa.Text(), nullable=True),
    sa.Column('contato_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('contato_email', sa.String(length=150), nullable=True),
    sa.Column('contato_linkedin', sa.String(length=255), nullable=True),
    sa.Column('contato_instagram', sa.String(length=100), nullable=True),
    sa.Column('contato_extra', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('telefone1', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('competencias_tecnicas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=False),
    sa.Column('imagem_destaque_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('candidatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaga_objetivo', sa.String(length=255), nullable=False),
    sa.Column('resumo_profissional', sa.Text(), nullable=True),
    sa.Column('curriculo_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('data_candidatura', sa.DateTime(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('instituicao', sa.String(length=150), nullable=True),
    sa.Column('carga_horaria', sa.String(length=20), nullable=True),
    sa.Column('ano_conclusao', sa.String(length=10), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('data_inicio', sa.String(length=20), nullable=True),
    sa.Column('data_fim', sa.String(length=20), nullable=True),
    sa.Column('atividades', sa.Text(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso', sa.String(length=150), nullable=False),
    sa.Column('instituicao', sa.String(length=150), nullable=False),
    sa.Column('ano_conclusao', sa.String(length=10), nullable=True),
    sa.Column('conclusao_prevista', sa.String(length=10), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idioma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idioma')
    op.drop_table('formacao')
    op.drop_table('experiencia')
    op.drop_table('curso')
    op.drop_table('candidatura')
    op.drop_table('user')
    op.drop_table('post')
    op.drop_table('pessoa')
    op.drop_table('especialista')
    # ### end Alembic commands ###
