"""Adiciona campo area ao modelo Especialista

Revision ID: 4968f0a5c13e
Revises: 
Create Date: 2025-11-02 12:54:53.170333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4968f0a5c13e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=50), nullable=False, server_default='outro'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialista', schema=None) as batch_op:
        batch_op.drop_column('area')

    # ### end Alembic commands ###
