"""Move resumo_profissional de Pessoa para Candidatura

Revision ID: db5b3e55a411
Revises: e5abbab13d35
Create Date: 2025-11-09 17:35:29.699378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5b3e55a411'
down_revision = 'e5abbab13d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumo_profissional', sa.Text(), nullable=True))

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('resumo_profissional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumo_profissional', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('candidatura', schema=None) as batch_op:
        batch_op.drop_column('resumo_profissional')

    # ### end Alembic commands ###
