"""Adiciona resumo_profissional ao modelo Pessoa

Revision ID: e5abbab13d35
Revises: 4968f0a5c13e
Create Date: 2025-11-09 16:42:16.027166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5abbab13d35'
down_revision = '4968f0a5c13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatura', schema=None) as batch_op:
        batch_op.drop_column('resumo_profissional')

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumo_profissional', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('resumo_profissional')

    with op.batch_alter_table('candidatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumo_profissional', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
